### ISSUE TITLE
Connection Check with Proxy Implementation 

### ISSUE THREAD

**Issue by bunzymr** [CiscoSecurity/amp-05-health-checker-windows#1]
We are using Cisco AMP in our organization with the Basic Authentication settings for the proxy. (more than 1000 Devices)
Every time I run the amp-05-health-checker-windows --> Connectivity Test, All the website status is
[CiscoAMPConnectivityTestRED.docx](https://github.com/CiscoSecurity/amp-05-health-checker-windows/files/6559424/CiscoAMPConnectivityTestRED.docx)
 "RED".
Could you please help to fix it?

**Comment by smalluk** [comment]
Ensure you have the correct AMP Cloud selected for your region, America/EU/APAC

**Comment by mafranks** [comment]
I've never attempted proxy implementation so this will likely need done by another contributor if anyone would like to take a crack at it.
