### ISSUE TITLE
Option to list connector UUID

### ISSUE THREAD

**Issue by vivsing4** [CiscoSecurity/amp-05-health-checker-windows#12]
Please enable an option to list the connector UUID as it will be useful in tracking or troubleshooting Duplicate UUID issues.
refer: https://techzone.cisco.com/t5/AMP-Public-Cloud/Steps-to-find-UUID-of-Cisco-Secure-Endpoint-Connector-of-an/ta-p/1917314

**Comment by mafranks** [comment]
The data is already pulled in the pasre_xml method of the Data class. 
            "policy_uuid": ("Object", "config", "janus", "policy", "uuid"),
Would just need to display it properly.  I don't think anyone is actively working on supporting this product if you'd like to implement that yourself @vivsing4

**Comment by vivsing4** [comment]
Thank you @mafranks for pointing that out. I will try to implement it and update you back.🤝
