### ISSUE TITLE
Option to save the API creds

### ISSUE THREAD

**Issue by vivsing4** [CiscoSecurity/amp-05-health-checker-windows#13]
Having an option to save the API creds will help as the tool currently asks to feed the API creds everytime it is re-run.
Probably, have api_creds.conf file and give user and option to save the creds in it. 
If the api_creds.conf is not found by the tool then prompt for entering creds to be provided.

**Comment by mafranks** [comment]
This is already available.  Check #2 in the API Credentials section of the README
