### ISSUE TITLE
Unhandled exception in script - exe

### ISSUE THREAD

**Issue by Lemmontree1981** [CiscoSecurity/amp-05-health-checker-windows#17]
When i start the exe file i get the following error:

![image](https://user-images.githubusercontent.com/60471611/213106802-313015ab-8037-4cc4-9bca-e536a6186c7d.png)

**Comment by mafranks** [comment]
Looks like you didn't create the .env file, or didn't create it properly.  Read through the README for instructions. I'll look at making a better error message.
