### ISSUE TITLE
Admin required error

### ISSUE THREAD

**Issue by sneekysob** [CiscoSecurity/amp-05-health-checker-windows#18]
Hey there,

Receiving the error "Changing log level requires running AMP Health Checker as Admin. Please try again as Admin." but I am in fact running as admin. Dug through the checker_log.log and found it was trying to run the sfc.exe in the 8.0.1.21164 folder but due to me having to roll back, I am now on 7.5.7.21234. Looks like when the connector gets updated the folders are not getting deleted as I have the last 4 version folders still in place. They still contain global.xml && SecurityProductInformation.ini. I briefly looked at the data.py file and noticed it's looking for the highest_build so wasn't sure if there is a workaround or something I could change to test. 

Thanks and appreciate the tool!

**Comment by mafranks** [comment]
Hey @sneekysob.  There is nothing important in those directories if you've rolled back so you can just delete anything higher than the latest build and it should work just fine.  Thanks for using the tool!  It is a labor of love.

**Comment by sneekysob** [comment]
Thanks for the response - I was hoping for a more wider search for the sfc.exe but you're right, the folders should be cleaned up anyways. Thanks again and cheers!

**Comment by mafranks** [comment]
I'll keep this issue open.  It is possible to add some logic to check for the directory containing sfc.exe and setting that as the proper working directory.  I'll add it to the TO DO list.  No promises on timeline.

**Comment by mafranks** [comment]
Fixed in 03October2023 version.
