### ISSUE TITLE
Unable to pull the policy guid due to KeyError

### ISSUE THREAD

**Issue by goa456** [CiscoSecurity/amp-05-health-checker-windows#20]
Hello, 

We use Secure Endpoint Version 8.1.5 on our Clients, I created API Credentials in the Secure Endpoint Console and SecureX Console.
When I start the AMP Health Checker I see the Error "Unable to pull the policy guid due to KeyError".

![image](https://user-images.githubusercontent.com/3693641/221872674-43923718-16ff-4697-bf8c-4ad9349accca.png)

I am not sure if the API Credentials have enough Privilege.
In the Documentation I also could not find any info what privilege is requiered for the API Credentials to work.
Do have any info what scopes and what checkboxes need to be enabled when creating the API Credentials in Secure Endpoint and SecureX.

Thanks.

**Comment by mafranks** [comment]
This KeyError should only appear if there is an issue pulling the policy guid from the Secure Endpoints API.  For this to happen there is likely an issue with the CLIENT_ID or API_KEY set in your .env file.  I tested with the least privileged API key (read only) in Secure Endpoints and it worked fine.  If you are able to change the Log Level on the tool to DEBUG before you see this error, there should be more information in the amp_health_checker_log.log file indicating what the API call is returning.

**Comment by mafranks** [comment]
Closing due to lack of information to investigate further.
