### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by gautamzone** [CiscoSecurity/amp-05-health-checker-windows#3]
Thanks for this great tool!

Can we add proxy support for this tool as well?
Without proxy support, there are two things not working:

1. API - which consequently means no Tetra version fetch, no policy number fetch and no isolation unlock code fetch
2. Connectivity Test button is showing red for all the 17 *.amp.cisco.com domains.  

![image](https://user-images.githubusercontent.com/74028919/127180438-d0bd506d-d071-4fa4-aa47-a3c4ddbcfa2c.png)

**Comment by mafranks** [comment]
I've never attempted proxy implementation so this will likely need done by another contributor if anyone would like to take a crack at it.

**Comment by mafranks** [comment]
Closing as duplicate of Issue #1
