### ISSUE TITLE
Tetra definitions are 72 updates behind but still shows yellow instead of red

### ISSUE THREAD

**Issue by gautamzone** [CiscoSecurity/amp-05-health-checker-windows#8]
![Pasted Graphic 1](https://user-images.githubusercontent.com/74028919/128077661-71a651e3-613b-46bb-9ef2-3038fce038bc.png)

08-03 20:42:39 root         DEBUG    data.py tetra_def_compare tetra_latest: 85334
08-03 20:42:39 root         DEBUG    data.py tetra_def_compare data.tetra_version: 85262
08-03 20:42:39 root         DEBUG    data.py tetra_def_compare data.tetra_version: 85262

**Comment by mafranks** [comment]
This is as designed.  Anything more than 5 versions old will be yellow.  The only reason it would be red is if TETRA is disabled in the policy.
