### ISSUE TITLE
Readme.md suggestions

### ISSUE THREAD

**Issue by gautamzone** [CiscoSecurity/amp-05-health-checker-windows#9]
Can you add a note to readme.md that you need to run as administrator as below?

![image](https://user-images.githubusercontent.com/74028919/128077973-5950a90a-2178-4489-9d5b-1249cf13d896.png)

In the absence of not running as administrator, i was never able to Generate Diagnostic from the health check tool. I was always faced with the error:

![image](https://user-images.githubusercontent.com/74028919/128078170-d034e894-ba89-40c6-a90f-db722709e9f1.png)

**Comment by mafranks** [comment]
Added information to Readme
